Project biobank {
  database_type: "PostgreSQL"
}

Table Пользователи {
  id             serial       [pk]
  username       varchar(120) [not null, unique]
  password_hash  varchar(128) [not null]
  birthday       date
  created_at     timestamptz  [not null, default: `now()`]
}

Table samples {
  id           serial       [pk]
  code         varchar(64)  [not null, unique]
  donor_id     int          [not null, ref: > users.id]
  collected_at timestamptz  [not null]
  stored_at    varchar(64)
}
